"""Standalone HTML rendering of a :class:`~datasonde.models.DatasetProfile`.

The renderer is a pure function built on the standard library only. Every dynamic
string goes through :func:`html.escape`; numbers are formatted by this module. No cell
value is ever rendered: only column names, dtype strings, numbers and warning texts.
The output has no script, no external resource and no timestamp, so the same input
always gives the same string.
"""

import html
from collections import Counter

from datasonde.models import ColumnInfo, ColumnProfile, DatasetProfile, DtypeFamily

# --- Visible texts (single place, to ease a future translation) -----------------------

TITLE = "DataSonda profiling report"
OVERVIEW_HEADING = "Overview"
COLUMNS_HEADING = "Columns"
WARNINGS_HEADING = "Warnings"
LIMITS_HEADING = "Limits of this analysis"
LABEL_ROWS = "Rows"
LABEL_COLUMNS = "Columns"
LABEL_MEMORY = "Memory"
LABEL_FAMILY_COUNT = "Columns by family"
TABLE_CAPTION = "Basic profile of each column, in original order"
HEADERS = ("Column", "Family", "Pandas dtype", "Memory", "Missing", "Distinct values", "Warnings")
NOT_AVAILABLE = "n/a"
NO_WARNING = "-"
FOOTER = "Generated by DataSonda"
LIMITS = (
    "Families are technical, derived from the pandas dtype. There is no type or role "
    "inference: for example, a boolean column containing nulls appears as text_or_object.",
    "Missing means a pandas null only. Empty strings, N/A and other sentinel values "
    "are not counted.",
    "There are no quality alerts, univariate statistics or charts yet.",
    "Distinct values exclude missing values.",
    "No raw cell value is displayed.",
)

CONTENT_SECURITY_POLICY = "default-src 'none'; style-src 'unsafe-inline'"

# Minimum visible bar width (in %) for a non-zero missing rate.
MIN_BAR_WIDTH = 1.0

_STYLE = """\
body { font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
  color: #1f2933; background: #ffffff; margin: 0; line-height: 1.5; }
main { max-width: 72rem; margin: 0 auto; padding: 1.5rem 1rem; }
h1 { margin: 0 0 0.25rem; }
h2 { margin: 2rem 0 0.75rem; border-bottom: 1px solid #d9dee3; padding-bottom: 0.25rem; }
.dataset-name { margin: 0; color: #52606d; font-size: 1.1rem; }
dl.overview { display: grid; grid-template-columns: max-content 1fr; gap: 0.25rem 1rem; }
dl.overview dt { font-weight: 600; }
dl.overview dd { margin: 0; }
.table-wrap { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: 0.9rem; }
caption { text-align: left; color: #52606d; padding-bottom: 0.5rem; }
th, td { border: 1px solid #d9dee3; padding: 0.35rem 0.6rem; text-align: left;
  vertical-align: top; }
th { background: #f0f4f8; }
td.num { text-align: right; white-space: nowrap; }
.bar { display: block; height: 0.4rem; margin-top: 0.25rem; background: #e4e7eb; }
.bar span { display: block; height: 100%; background: #627d98; }
footer { margin-top: 2rem; color: #52606d; font-size: 0.85rem; }
"""


# --- Formatting helpers -----------------------------------------------------------------


def format_bytes(n: int) -> str:
    """Format a byte count in base 1024: ``0 B``, ``1023 B``, ``1.0 KiB``, ``MiB``..."""
    if n < 1024:
        return f"{n} B"
    value = float(n)
    for unit in ("KiB", "MiB", "GiB"):
        value /= 1024
        if value < 1024:
            return f"{value:.1f} {unit}"
    return f"{value / 1024:.1f} TiB"


def format_percent(rate: float | None) -> str:
    """Format a rate in [0, 1] as a percentage with one decimal.

    ``None`` gives ``n/a``. Exact 0 and 1 give ``0.0%`` and ``100.0%``; a non-zero
    rate that would round to ``0.0%`` gives ``<0.1%`` and a rate below 1 that would
    round to ``100.0%`` gives ``>99.9%``, so rounding never hides a partial column.
    """
    if rate is None:
        return NOT_AVAILABLE
    if rate <= 0:
        return "0.0%"
    if rate >= 1:
        return "100.0%"
    text = f"{rate * 100:.1f}"
    if text == "0.0":
        return "<0.1%"
    if text == "100.0":
        return ">99.9%"
    return f"{text}%"


def bar_width(rate: float | None) -> float | None:
    """Width of the missing-rate bar in percent, or ``None`` when there is no bar.

    The width is ``rate * 100`` bounded to [0, 100]. A non-zero rate gets at least
    ``MIN_BAR_WIDTH`` so that it stays visible.
    """
    if rate is None:
        return None
    width = min(max(rate * 100, 0.0), 100.0)
    if rate > 0:
        width = max(width, MIN_BAR_WIDTH)
    return width


# --- Rendering --------------------------------------------------------------------------


def _esc(text: str) -> str:
    return html.escape(text, quote=True)


def _render_overview(profile: DatasetProfile) -> list[str]:
    meta = profile.metadata
    counts = Counter(column.family for column in profile.columns)
    families = ", ".join(
        f"{_esc(family.value)}: {counts[family]}" for family in DtypeFamily if counts[family]
    )
    return [
        f"<h2>{OVERVIEW_HEADING}</h2>",
        '<dl class="overview">',
        f"<dt>{LABEL_ROWS}</dt><dd>{meta.n_rows:,}</dd>",
        f"<dt>{LABEL_COLUMNS}</dt><dd>{meta.n_columns:,}</dd>",
        f"<dt>{LABEL_MEMORY}</dt><dd>{format_bytes(meta.memory_bytes)}</dd>",
        f"<dt>{LABEL_FAMILY_COUNT}</dt><dd>{families or NOT_AVAILABLE}</dd>",
        "</dl>",
    ]


def _render_missing(column: ColumnProfile) -> str:
    cell = f"{column.n_missing:,} ({format_percent(column.missing_rate)})"
    width = bar_width(column.missing_rate)
    if width is None:
        return cell
    bar = f'<span class="bar" aria-hidden="true"><span style="width:{width:.1f}%"></span></span>'
    return cell + bar


def _render_row(column: ColumnProfile, info: ColumnInfo) -> str:
    distinct = NOT_AVAILABLE if column.n_unique is None else f"{column.n_unique:,}"
    warnings = (
        "".join(f"<div>{_esc(w)}</div>" for w in column.warnings) if column.warnings else NO_WARNING
    )
    return (
        "<tr>"
        f"<td>{_esc(column.name)}</td>"
        f"<td>{_esc(column.family.value)}</td>"
        f"<td>{_esc(info.dtype)}</td>"
        f'<td class="num">{format_bytes(info.memory_bytes)}</td>'
        f'<td class="num">{_render_missing(column)}</td>'
        f'<td class="num">{distinct}</td>'
        f"<td>{warnings}</td>"
        "</tr>"
    )


def _render_table(profile: DatasetProfile) -> list[str]:
    head = "".join(f'<th scope="col">{_esc(h)}</th>' for h in HEADERS)
    rows = [
        _render_row(column, info)
        for column, info in zip(profile.columns, profile.metadata.columns, strict=True)
    ]
    return [
        f"<h2>{COLUMNS_HEADING}</h2>",
        '<div class="table-wrap">',
        "<table>",
        f"<caption>{_esc(TABLE_CAPTION)}</caption>",
        f"<thead><tr>{head}</tr></thead>",
        "<tbody>",
        *rows,
        "</tbody>",
        "</table>",
        "</div>",
    ]


def _render_warnings(profile: DatasetProfile) -> list[str]:
    items = [
        f"<li>{_esc(column.name)}: {_esc(warning)}</li>"
        for column in profile.columns
        for warning in column.warnings
    ]
    if not items:
        return []
    return [f"<h2>{WARNINGS_HEADING}</h2>", "<ul>", *items, "</ul>"]


def _render_limits() -> list[str]:
    items = [f"<li>{_esc(text)}</li>" for text in LIMITS]
    return [f"<h2>{LIMITS_HEADING}</h2>", "<ul>", *items, "</ul>"]


def render_html(profile: DatasetProfile, *, name: str | None, version: str) -> str:
    """Render ``profile`` as a standalone HTML page.

    Pure and deterministic: no timestamp, no script, no external resource. ``name`` is
    the optional dataset name and ``version`` the DataSonda version shown in the footer.
    """
    title = TITLE if name is None else f"{TITLE} - {name}"
    body = [
        f"<h1>{TITLE}</h1>",
        *([f'<p class="dataset-name">{_esc(name)}</p>'] if name is not None else []),
        *_render_overview(profile),
        *_render_table(profile),
        *_render_warnings(profile),
        *_render_limits(),
        f"<footer>{FOOTER} {_esc(version)}</footer>",
    ]
    lines = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f'<meta http-equiv="Content-Security-Policy" content="{_esc(CONTENT_SECURITY_POLICY)}">',
        f"<title>{_esc(title)}</title>",
        f"<style>\n{_STYLE}</style>",
        "</head>",
        "<body>",
        "<main>",
        *body,
        "</main>",
        "</body>",
        "</html>",
    ]
    return "\n".join(lines) + "\n"
